//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Y
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product.
    /// </summary>
    // *** Start programmer edit section *** (Product CustomAttributes)

    // *** End programmer edit section *** (Product CustomAttributes)
    [AutoAltered()]
    [Caption("Товары")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ProductE", new string[] {
            "Name as \'Название\'",
            "Price as \'Цена\'"})]
    [View("ProductL", new string[] {
            "Name as \'Название\'",
            "Price as \'Цена\'"})]
    public class Product : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private double fPrice;
        
        // *** Start programmer edit section *** (Product CustomMembers)

        // *** End programmer edit section *** (Product CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Product.Name CustomAttributes)

        // *** End programmer edit section *** (Product.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Product.Name Get start)

                // *** End programmer edit section *** (Product.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Product.Name Get end)

                // *** End programmer edit section *** (Product.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Name Set start)

                // *** End programmer edit section *** (Product.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Product.Name Set end)

                // *** End programmer edit section *** (Product.Name Set end)
            }
        }
        
        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (Product.Price CustomAttributes)

        // *** End programmer edit section *** (Product.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (Product.Price Get start)

                // *** End programmer edit section *** (Product.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (Product.Price Get end)

                // *** End programmer edit section *** (Product.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Product.Price Set start)

                // *** End programmer edit section *** (Product.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (Product.Price Set end)

                // *** End programmer edit section *** (Product.Price Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductE", typeof(IIS.Y.Product));
                }
            }
            
            /// <summary>
            /// "ProductL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductL", typeof(IIS.Y.Product));
                }
            }
        }
    }
}
