//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Y
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Saleitem.
    /// </summary>
    // *** Start programmer edit section *** (Saleitem CustomAttributes)

    // *** End programmer edit section *** (Saleitem CustomAttributes)
    [AutoAltered()]
    [Caption("Товарная позиция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SaleitemE", new string[] {
            "Amount as \'Количество\'",
            "Product as \'Товар\'",
            "Product.Name as \'Товар\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("SaleitemE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Saleitem : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.Y.Product fProduct;
        
        private IIS.Y.Sale fSale;
        
        // *** Start programmer edit section *** (Saleitem CustomMembers)

        // *** End programmer edit section *** (Saleitem CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (Saleitem.Amount CustomAttributes)

        // *** End programmer edit section *** (Saleitem.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (Saleitem.Amount Get start)

                // *** End programmer edit section *** (Saleitem.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (Saleitem.Amount Get end)

                // *** End programmer edit section *** (Saleitem.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Saleitem.Amount Set start)

                // *** End programmer edit section *** (Saleitem.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (Saleitem.Amount Set end)

                // *** End programmer edit section *** (Saleitem.Amount Set end)
            }
        }
        
        /// <summary>
        /// Saleitem.
        /// </summary>
        // *** Start programmer edit section *** (Saleitem.Product CustomAttributes)

        // *** End programmer edit section *** (Saleitem.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        [NotNull()]
        public virtual IIS.Y.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (Saleitem.Product Get start)

                // *** End programmer edit section *** (Saleitem.Product Get start)
                IIS.Y.Product result = this.fProduct;
                // *** Start programmer edit section *** (Saleitem.Product Get end)

                // *** End programmer edit section *** (Saleitem.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Saleitem.Product Set start)

                // *** End programmer edit section *** (Saleitem.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (Saleitem.Product Set end)

                // *** End programmer edit section *** (Saleitem.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Y.Sale.
        /// </summary>
        // *** Start programmer edit section *** (Saleitem.Sale CustomAttributes)

        // *** End programmer edit section *** (Saleitem.Sale CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Sale"})]
        public virtual IIS.Y.Sale Sale
        {
            get
            {
                // *** Start programmer edit section *** (Saleitem.Sale Get start)

                // *** End programmer edit section *** (Saleitem.Sale Get start)
                IIS.Y.Sale result = this.fSale;
                // *** Start programmer edit section *** (Saleitem.Sale Get end)

                // *** End programmer edit section *** (Saleitem.Sale Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Saleitem.Sale Set start)

                // *** End programmer edit section *** (Saleitem.Sale Set start)
                this.fSale = value;
                // *** Start programmer edit section *** (Saleitem.Sale Set end)

                // *** End programmer edit section *** (Saleitem.Sale Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SaleitemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SaleitemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SaleitemE", typeof(IIS.Y.Saleitem));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Saleitem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSaleitem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSaleitem CustomAttributes)
    public class DetailArrayOfSaleitem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Y.DetailArrayOfSaleitem members)

        // *** End programmer edit section *** (IIS.Y.DetailArrayOfSaleitem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Saleitem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Saleitem.
        /// </summary>
        public DetailArrayOfSaleitem(IIS.Y.Sale fSale) : 
                base(typeof(Saleitem), ((ICSSoft.STORMNET.DataObject)(fSale)))
        {
        }
        
        public IIS.Y.Saleitem this[int index]
        {
            get
            {
                return ((IIS.Y.Saleitem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Y.Saleitem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
